Repository slipstream/SlipStream, pull requests merged in 2018-05, with the labels that each got.

#299 multiple indexes in ES
  clojure-deps/build.boot
  clojure-deps/pom.xml
  clojure-deps/src/main/resources/default-deps.edn
  pom.xml
Labels: P66 EU-SEC, S40 Ready to validate

#301 cleanup and align clj deps versions with SlipStreamParent
  pom.xml
Labels: S40 Ready to validate

#302 use correct string comparison operator
  install/slipstream.sh
Labels: P45 MF2C, T5 Bug

#303 fix configuration of reports parameters
  install/ss-ci-pipeline/ss-deployer.sh
Labels: P45 MF2C, T5 Bug
